apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: dbot-deployment
spec:
  selector:
    matchLabels:
      app: dbot
  replicas: 1
  template:
    metadata:
      labels:
        app: dbot
    spec:
      containers:
        - name: dbot
          image: bghji/dbot:latest
          volumeMounts:
            - name: channel-config
              mountPath: "/etc/dbot-config"
              readOnly: true
          env:
            - name: DBOT_DISCORD_TOKEN
              value: "NzQwMDk2Mzk2MzUwMTkzNzA0.XykCew.sViApzplL772x-kTHpWbAwSXrdU"
            - name: DBOT_REDIS_URL
              value: redis://redis-master
            - name: DBOT_ENV_CONFIG
              value: "true"
            - name: DBOT_CHANNEL_CONFIG_PATH
              value: "/etc/dbot-config/config"
      volumes:
        - name: channel-config
          configMap:
            name: dbot-channel-config
