version: "3.9"
services:
  dbot:
    build: .
    command: python app/main.py
    env_file:
      - ./values/local.env
    profiles: ["app"]
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    profiles: ["infra"]