version: "3.2"
services:
  dbot:
    build: ./app
    command: python main.py
    environment:
      DBOT_DISCORD_TOKEN: "NzQwMDk2Mzk2MzUwMTkzNzA0.XykCew.sViApzplL772x-kTHpWbAwSXrdU"
      DBOT_REDIS_URL: "redis://redis"
      DBOT_ENV_CONFIG: "true"
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"