name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'

      - name: Install poetry
        run: pip install poetry

      - name: Configure poetry
        run: poetry config virtualenvs.create false

      - name: Install dependencies
        run: cd app && poetry install

      - name: return to root folder
        run: cd ..

      - name: Run lint
        run: make lint

      - name: Run tests
        run: make test


