name: Build

on: [ push ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
          architecture: 'x64'

      - name: Install poetry
        run: make poetry

      - name: Configure poetry
        run: poetry config virtualenvs.create false

      - name: Install dependencies
        run: make install-dev

      - name: Run lint
        run: make lint

  test-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
          architecture: 'x64'

      - name: Install poetry
        run: make poetry

      - name: Configure poetry
        run: poetry config virtualenvs.create false

      - name: Install dependencies
        run: make install-dev

      - name: Activate CI environment
        uses: c-py/action-dotenv-to-setenv@v2
        with:
          env-file: .env.ci

      - name: Run tests
        run: make test/unit

  test-integration:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
          architecture: 'x64'

      - name: Install poetry
        run: make poetry

      - name: Configure poetry
        run: poetry config virtualenvs.create false

      - name: Install dependencies
        run: make install-dev

      - name: Run tests
        run: make test/integration

  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Run build docker
        run: make docker/build


