name: CI

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
          architecture: 'x64'

      - name: Install poetry
        run: make poetry

      - name: Configure poetry
        run: poetry config virtualenvs.create false

      - name: Install dependencies
        run: make install-dev

      - name: Run lint
        run: make lint

      - name: Run tests
        run: make test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Run build docker
        run: make docker/build


